databases:
  - name: postgres
    databaseName: web_drop_dead_db
    user: harir99

services:
  - type: web
    name: WebDropDead
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      key: DATABASE_URL
        fromDatabase:
          name: WebDropDead
          property: connectionString
      value: postgres://web_drop_dead_db_user:wQDsNbn5aNlZdziaidzmzQaGUmPGe88p@dpg-clhmilebbf9s73b25img-a/web_drop_dead_db
      - key: RAILS_MASTER_KEY
        sync: false
