databases:
  - name: postgres
    # databaseName: WebDropDead
    # user: WebDropDead

services:
  - type: web
    name: WebDropDead
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: WebDropDead
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
